### ISSUE TITLE
Integrate tri-state with the morph behavior

### ISSUE THREAD

**Issue by Townk** [dhruvinsh/zmk-swapper#1]
I loved this concept of stand-alone modules for ZMK on this package, and it made me wonder if it's possible to achieve a deeper integration with current behaviors this way.

What I would like to achieve is the following. Assume I have two keys:

```
+----+  +----+
| K1 |  | K2 |
+----+  +----+
```

- `K1` is a tri-sate that will produce the `Alt+Tab` (or `Cmd+Tab` on Macs);
- `K2` is a "morph-key" that, when pressed by itself, produces `A`, but if pressed while holding `Alt` (or `Cmd` on Macs), then it will produce a `Shift+Alt+Tab` (or `Shift+Cmd+Tab` or `Cmd+Grave` on Macs);

This is pretty straightforward today, and works like a charm:

```
/ {
  behaviors {
    appswtnxt: application_switch_next {
      compatible = "zmk,behavior-tri-state";
      #binding-cells = <0>;
      bindings = <&kt LGUI>, <&kp TAB>, <&kt LGUI>;
      ignored-key-positions = <LT5 LM5>;
    };

    winswtnxt: window_switch_next {
      compatible = "zmk,behavior-tri-state";
      #binding-cells = <0>;
      bindings = <&kt LGUI>, <&kp GRAVE>, <&kt LGUI>;
      ignored-key-positions = <LB5 LM5>;
    };

    appPwinN: application_switch_previous_window_next {
      compatible = "zmk,behavior-mod-morph";
      #binding-cells = <0>;
      bindings = <&winswtnxt>, <&kp GRAVE>;
      mods = <(MOD_LGUI|MOD_RGUI)>;
      keep-mods = <(MOD_LGUI|MOD_RGUI)>;
    };

    keymap {
        compatible = "zmk,keymap";
        label ="Default keymap";

        default_layer {
            bindings = <
                &appswtnxt  &appPwinN
        };
    };
};
```

Now, I'm not sure if Windows or Linux have such a concept, but on macOS, when you press `Cmd+Grave` (usually the key above the `Tab`), it starts the same _"app switching"_ but only for the windows of the current application. Once started, the window switch works like an app switch, including the reverse behavior when holding down the Shift key.

I want to configure `K2` to start this window-switch action with a tri-state, and use `K1` for the reverse behavior.

In this case, because the key held down is the same on both behaviors, if I use the same trick with "morph" keys on `K1`, it will break the main behavior of if because when the tri-state for switching applications starts, it will have the `Cmd` key held-down, so the "morph" behavior will convert the key into its "window switching" variant.

Ideally, I would like to change `morph` to allow me to specify a tri-state behavior, that, when active, it will force the key to use its alternative value. Something like this:

```
/ {
  behaviors {
    appswtnxt: application_switch_next {
      compatible = "zmk,behavior-tri-state";
      #binding-cells = <0>;
      bindings = <&kt LGUI>, <&kp TAB>, <&kt LGUI>;
      ignored-key-positions = <LT5 LM5>;
    };

    winswtnxt: window_switch_next {
      compatible = "zmk,behavior-tri-state";
      #binding-cells = <0>;
      bindings = <&kt LGUI>, <&kp GRAVE>, <&kt LGUI>;
      ignored-key-positions = <LB5 LM5>;
    };

    appPwinN: application_switch_previous_window_next {
      compatible = "zmk,behavior-mod-morph";
      #binding-cells = <0>;
      bindings = <&winswtnxt>, <&kp LG(GRAVE)>;
      tri_state = <&appswtnxt>;
    };

    winPappN: window_switch_previous_app_next {
      compatible = "zmk,behavior-mod-morph";
      #binding-cells = <0>;
      bindings = <&appswtnxt>, <&kp LG(LS(GRAVE))>;
      tri_state = <&winswtnxt>;
    };

    keymap {
        compatible = "zmk,keymap";
        label ="Default keymap";

        default_layer {
            bindings = <
                &winPappN  &appPwinN
        };
    };
};
```

Now, if I set `K1` to `&appPwinN` and `K2` to `&winPappN`, I can use just those two keys to handle two types of tri-state behavior that uses the same holding-down key.

Can we achieve something like this with this type of module repository? If not, what would be your suggestion for this?

**Comment by dhruvinsh** [comment]
> I loved this concept of stand-alone modules for ZMK on this package

@Townk I appreciate your positive word.

> it made me wonder if it's possible to achieve a deeper integration with current behaviors this way.

Yes with standalone module anything can be possible. Thank you for taking time and pointing out your awesome idea.

But I would like to point out, as of right now I do not have enough knowledge to implement your concept or answer if its even possible. I created this project with one single goal, that if standalone module can be implemented or not. 

This project was fun where I learn lot of new thing like devicetree, cmake and use of special directory in zypher. Got to read the zypher docs and it is huge!! But adding something new on this project would be out of scope and out of my knowledge as well.

I encourage you to for this repo and implement new feature to your liking. :) all the best.
